apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
#  storageClassName: pv-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

# Class: A PV can have a class, which is specified by setting the storageClassName attribute to the name of a StorageClass. A PV of a particular class can only be bound to PVCs requesting that class. 
# A PV with no storageClassName has no class and can only be bound to PVCs that request no particular class